"use client";

import Link from "next/link";
import { ArrowLeft, ExternalLink, Plus, Save, Trash2 } from "lucide-react";
import { useActionState, useState } from "react";
import { saveAdminGuide } from "@/actions/admin-guides";
import { useAdminLanguage } from "@/components/admin/admin-i18n";
import { guideReadingTime, type AdminGuide, type AdminGuideActionState, type GuideContent } from "@/lib/admin/guide-editor";
import "@/components/admin/guide-admin.css";

const initialState: AdminGuideActionState = { status: "idle", message: "" };

export function AdminGuideEditor({ guide, canManage, saved }: { guide?: AdminGuide; canManage: boolean; saved: boolean }) {
  const { locale } = useAdminLanguage();
  const fr = locale === "fr";
  const [state, action, pending] = useActionState(saveAdminGuide, initialState);
  const [sections, setSections] = useState(() => guide?.sections.map((section) => ({ title: section.title, text: section.paragraphs.join("\n\n") })) ?? [{ title: "", text: "" }]);
  const [hasTable, setHasTable] = useState(Boolean(guide?.comparison));
  const [comparison, setComparison] = useState<NonNullable<GuideContent["comparison"]>>(() => guide?.comparison ?? { title: "", caption: "", columns: ["", ""], rows: [["", ""]] });
  const content: GuideContent = {
    readingTime: "",
    sections: sections.map((section) => ({ title: section.title, paragraphs: section.text.split(/\n\s*\n/).map((value) => value.trim()).filter(Boolean) })),
    comparison: hasTable ? comparison : null,
  };
  content.readingTime = guideReadingTime(content);
  function changeSection(index: number, values: Partial<(typeof sections)[number]>) { setSections((current) => current.map((section, position) => position === index ? { ...section, ...values } : section)); }
  function changeCell(rowIndex: number, columnIndex: number, value: string) { setComparison((current) => ({ ...current, rows: current.rows.map((row, position) => position === rowIndex ? row.map((cell, column) => column === columnIndex ? value : cell) : row) })); }

  return <div className="admin-guide-cms">
    <Link className="text-link" href="/admin/vodici"><ArrowLeft size={16} />{fr ? "Tous les guides" : "Vsi vodniki"}</Link>
    <header className="admin-page-heading"><div><p className="section-kicker">{fr ? "Édition du contenu" : "Urejanje vsebine"}</p><h1>{guide ? guide.title : fr ? "Créer un guide" : "Nov vodnik"}</h1><p>{fr ? "Le contenu public est en slovène. Séparez les paragraphes par une ligne vide." : "Javna vsebina je v slovenščini. Odstavke ločite s prazno vrstico."}</p></div>{guide?.status === "published" ? <Link className="button button-secondary" href={`/vodici/${guide.slug}`} target="_blank"><ExternalLink size={16} />{fr ? "Voir l’article" : "Poglej članek"}</Link> : null}</header>
    {saved ? <p className="admin-operation-message is-success" role="status">{fr ? "Guide enregistré. La publication est à jour." : "Vodnik je shranjen. Objava je posodobljena."}</p> : null}
    <form action={action} className="admin-guide-editor">
      <input name="adminLocale" type="hidden" value={locale} /><input name="id" type="hidden" value={guide?.id ?? ""} /><input name="expectedUpdatedAt" type="hidden" value={guide?.version ?? ""} /><input name="content" type="hidden" value={JSON.stringify(content)} />
      <fieldset disabled={pending || !canManage}>
        <section className="card"><h2>{fr ? "Présentation" : "Predstavitev"}</h2><label><span>{fr ? "Titre de l’article" : "Naslov članka"}</span><input defaultValue={guide?.title ?? ""} maxLength={200} minLength={3} name="title" required /></label><label><span>{fr ? "Adresse de l’article" : "Naslov povezave"}</span><input defaultValue={guide?.slug ?? ""} maxLength={180} name="slug" pattern="[a-z0-9]+(-[a-z0-9]+)*" readOnly={Boolean(guide)} required /><small>{fr ? "Exemple : kako-izbrati-vodni-filter. L’adresse reste stable après la création." : "Primer: kako-izbrati-vodni-filter. Povezava po ustvarjanju ostane nespremenjena."}</small></label><label><span>{fr ? "Résumé" : "Povzetek"}</span><textarea defaultValue={guide?.excerpt ?? ""} maxLength={600} minLength={15} name="excerpt" required rows={3} /></label><label><span>{fr ? "Publication" : "Objava"}</span><select defaultValue={guide?.status ?? "draft"} name="status"><option value="draft">{fr ? "Brouillon — non visible" : "Osnutek — ni javno viden"}</option><option value="published">{fr ? "Publié — visible dans la boutique" : "Objavljeno — vidno v trgovini"}</option><option value="archived">{fr ? "Archivé — retiré du site" : "Arhivirano — umaknjeno s spletnega mesta"}</option></select></label></section>
        <section className="card"><header className="admin-guide-section-heading"><h2>{fr ? "Sections de l’article" : "Poglavja članka"}</h2><small>{content.readingTime}</small></header>{sections.map((section, index) => <div className="admin-guide-section-editor" key={index}><header><strong>{fr ? "Section" : "Poglavje"} {index + 1}</strong><button aria-label={fr ? `Supprimer la section ${index + 1}` : `Odstrani poglavje ${index + 1}`} className="admin-guide-remove" disabled={sections.length === 1} onClick={() => setSections((current) => current.filter((_, position) => position !== index))} type="button"><Trash2 size={17} /></button></header><label><span>{fr ? "Sous-titre" : "Podnaslov"}</span><input maxLength={200} onChange={(event) => changeSection(index, { title: event.target.value })} required value={section.title} /></label><label><span>{fr ? "Paragraphes" : "Odstavki"}</span><textarea onChange={(event) => changeSection(index, { text: event.target.value })} required rows={7} value={section.text} /></label></div>)}<button className="button button-secondary" disabled={sections.length >= 40} onClick={() => setSections((current) => [...current, { title: "", text: "" }])} type="button"><Plus size={17} />{fr ? "Ajouter une section" : "Dodaj poglavje"}</button></section>
        <section className="card"><h2>{fr ? "Tableau comparatif" : "Primerjalna tabela"}</h2><label className="admin-guide-checkbox"><input checked={hasTable} onChange={(event) => setHasTable(event.target.checked)} type="checkbox" /><span>{fr ? "Afficher un tableau comparatif" : "Prikaži primerjalno tabelo"}</span></label>{hasTable ? <><label><span>{fr ? "Titre du tableau" : "Naslov tabele"}</span><input maxLength={200} onChange={(event) => setComparison((current) => ({ ...current, title: event.target.value }))} required value={comparison.title} /></label><label><span>{fr ? "Légende" : "Opis tabele"}</span><textarea maxLength={500} onChange={(event) => setComparison((current) => ({ ...current, caption: event.target.value }))} rows={2} value={comparison.caption} /></label><div className="admin-guide-table-scroll"><table><thead><tr>{comparison.columns.map((column, index) => <th key={index}><label><span>{fr ? "Colonne" : "Stolpec"} {index + 1}</span><input maxLength={150} onChange={(event) => setComparison((current) => ({ ...current, columns: current.columns.map((value, position) => position === index ? event.target.value : value) }))} required value={column} /></label></th>)}<th aria-label={fr ? "Actions" : "Dejanja"} /></tr></thead><tbody>{comparison.rows.map((row, rowIndex) => <tr key={rowIndex}>{row.map((cell, columnIndex) => <td key={columnIndex}><textarea aria-label={`${fr ? "Ligne" : "Vrstica"} ${rowIndex + 1}, ${fr ? "colonne" : "stolpec"} ${columnIndex + 1}`} maxLength={1000} onChange={(event) => changeCell(rowIndex, columnIndex, event.target.value)} rows={3} value={cell} /></td>)}<td><button aria-label={fr ? `Supprimer la ligne ${rowIndex + 1}` : `Odstrani vrstico ${rowIndex + 1}`} className="admin-guide-remove" disabled={comparison.rows.length === 1} onClick={() => setComparison((current) => ({ ...current, rows: current.rows.filter((_, position) => position !== rowIndex) }))} type="button"><Trash2 size={17} /></button></td></tr>)}</tbody></table></div><div className="admin-guide-table-actions"><button className="button button-secondary" disabled={comparison.rows.length >= 30} onClick={() => setComparison((current) => ({ ...current, rows: [...current.rows, current.columns.map(() => "")] }))} type="button"><Plus size={16} />{fr ? "Ajouter une ligne" : "Dodaj vrstico"}</button><button className="button button-secondary" disabled={comparison.columns.length >= 6} onClick={() => setComparison((current) => ({ ...current, columns: [...current.columns, ""], rows: current.rows.map((row) => [...row, ""]) }))} type="button">{fr ? "Ajouter une colonne" : "Dodaj stolpec"}</button><button className="button button-secondary" disabled={comparison.columns.length <= 2} onClick={() => setComparison((current) => ({ ...current, columns: current.columns.slice(0, -1), rows: current.rows.map((row) => row.slice(0, -1)) }))} type="button">{fr ? "Retirer la dernière colonne" : "Odstrani zadnji stolpec"}</button></div></> : null}</section>
        <section className="card"><h2>{fr ? "Référencement Google" : "Vidnost v Googlu"}</h2><label><span>{fr ? "Titre SEO" : "SEO naslov"}</span><input defaultValue={guide?.seoTitle ?? ""} maxLength={120} name="seoTitle" /><small>{fr ? "Laissez vide pour utiliser le titre de l’article." : "Pustite prazno za uporabo naslova članka."}</small></label><label><span>{fr ? "Description SEO" : "SEO opis"}</span><textarea defaultValue={guide?.seoDescription ?? ""} maxLength={300} name="seoDescription" rows={3} /><small>{fr ? "Laissez vide pour utiliser le résumé." : "Pustite prazno za uporabo povzetka."}</small></label></section>
        <button className="button button-primary admin-guide-save" disabled={pending || !canManage} type="submit"><Save size={18} />{pending ? fr ? "Enregistrement…" : "Shranjevanje…" : fr ? "Enregistrer le guide" : "Shrani vodnik"}</button>
      </fieldset>
      {state.message ? <p className="admin-operation-message is-error" role="alert">{state.message}</p> : null}
    </form>
  </div>;
}
