"use client";
import Link from "next/link";
import { ArrowRight, Package, ShoppingBag, Users, Wallet, Plus, Truck, TicketPercent, AlertCircle } from "lucide-react";
import { useAdminLanguage } from "./admin-i18n";
import type { AdminOverview } from "@/lib/admin/overview";
import "./operations.css";

export function AdminOverviewView({ data, checkoutEnabled, analytics = false }: { data: AdminOverview | null; checkoutEnabled: boolean; analytics?: boolean }) {
  const { locale } = useAdminLanguage();
  const fr = locale === "fr";
  const money = (value: number) => new Intl.NumberFormat(fr ? "fr-FR" : "sl-SI", { style: "currency", currency: "EUR" }).format(value / 100);
  if (!data) return <div className="notice" role="alert">{fr ? "Le tableau de bord ne peut pas charger les données. Actualisez la page ou vérifiez la connexion Supabase." : "Podatkov nadzorne plošče ni mogoče naložiti. Osvežite stran ali preverite povezavo Supabase."}</div>;
  const stats = [
    { icon: Wallet, value: money(data.revenue30), name: fr ? "Encaissements nets · 30 jours" : "Neto prejeta plačila · 30 dni", detail: fr ? "Paiements reçus, remboursements déduits" : "Prejeta plačila, zmanjšana za vračila" },
    { icon: ShoppingBag, value: data.orders30, name: fr ? "Commandes · 30 jours" : "Naročila · 30 dni", detail: `${data.openOrders} ${fr ? "commandes à suivre" : "odprtih naročil"}` },
    { icon: Package, value: data.publishedProducts, name: fr ? "Produits publiés" : "Objavljeni izdelki", detail: `${data.stockUnits} ${fr ? "unités en stock" : "kosov na zalogi"}` },
    { icon: Users, value: data.customers, name: fr ? "Clients" : "Kupci", detail: fr ? "Comptes clients et achats invités" : "Računi kupcev in gostujoči nakupi" },
  ];
  const max = Math.max(1, ...data.monthlySales.map(x => x.cents));
  return <>
    <header className="admin-page-heading"><div><p className="section-kicker">Bistrava · {fr ? "Gestion de la boutique" : "Upravljanje trgovine"}</p><h1>{analytics ? (fr ? "Rapports de vente" : "Poročila o prodaji") : (fr ? "Tableau de bord" : "Nadzorna plošča")}</h1><p>{fr ? "Vos ventes, vos produits et les opérations à traiter." : "Prodaja, izdelki in opravila na enem mestu."}</p></div><Link className="button button-primary" href="/admin/izdelki/nov"><Plus size={18} aria-hidden="true" />{fr ? "Créer un produit" : "Nov izdelek"}</Link></header>
    {!checkoutEnabled ? <div className="admin-preview-banner" role="status"><AlertCircle size={20} aria-hidden="true" /><div><strong>{fr ? "Prise de commandes désactivée" : "Oddaja naročil je izklopljena"}</strong><span>{fr ? "Vous pouvez administrer la boutique. Les ventes seront ouvertes après configuration des paiements et des livraisons." : "Trgovino lahko urejate. Naročanje bo omogočeno po nastavitvi plačil in dostave."}</span></div></div> : null}
    <section className="admin-stat-grid" aria-label={fr ? "Indicateurs" : "Kazalniki"}>{stats.map(({ icon: Icon, value, name, detail }) => <article className="admin-stat-card card" key={name}><span className="admin-stat-icon is-teal"><Icon size={22} aria-hidden="true" /></span><div><strong>{value}</strong><span>{name}</span></div><small>{detail}</small></article>)}</section>
    <nav className="ops-quick-links" aria-label={fr ? "Actions rapides" : "Hitre povezave"}><Link href="/admin/narocila"><ShoppingBag />{fr ? "Traiter les commandes" : "Obdelava naročil"}<ArrowRight /></Link><Link href="/admin/zaloga"><Package />{fr ? "Ajuster le stock" : "Uredite zalogo"}<ArrowRight /></Link><Link href="/admin/dostava"><Truck />{fr ? "Préparer les livraisons" : "Pripravite dostavo"}<ArrowRight /></Link><Link href="/admin/promocije"><TicketPercent />{fr ? "Gérer les promotions" : "Uredite promocije"}<ArrowRight /></Link></nav>
    <div className="ops-two-columns"><section className="admin-dashboard-panel card"><h2>{fr ? "Commandes récentes" : "Najnovejša naročila"}</h2>{data.recentOrders.length ? <div className="ops-table-wrap"><table className="ops-table"><thead><tr><th>{fr ? "Commande" : "Naročilo"}</th><th>{fr ? "Statut" : "Stanje"}</th><th>{fr ? "Total" : "Skupaj"}</th></tr></thead><tbody>{data.recentOrders.map(order => <tr key={order.id}><td><Link href={`/admin/narocila?order=${order.id}`}>{order.reference}</Link><small>{new Date(order.created_at).toLocaleDateString(fr ? "fr-FR" : "sl-SI")}</small></td><td>{({ pending: fr ? "À traiter" : "Novo", awaiting_payment: fr ? "Attente paiement" : "Čaka plačilo", paid: fr ? "Payée" : "Plačano", processing: fr ? "En préparation" : "V pripravi", shipped: fr ? "Expédiée" : "Odpremljeno", completed: fr ? "Terminée" : "Zaključeno", cancelled: fr ? "Annulée" : "Preklicano", refunded: fr ? "Remboursée" : "Vrnjeno", partially_refunded: fr ? "Remboursement partiel" : "Delno vračilo" } as Record<string, string>)[order.status] ?? order.status}</td><td>{money(order.total_cents)}</td></tr>)}</tbody></table></div> : <p className="ops-empty">{fr ? "Vos premières commandes apparaîtront ici." : "Tukaj bodo prikazana prva naročila."}</p>}<Link href="/admin/narocila">{fr ? "Toutes les commandes" : "Vsa naročila"} →</Link></section>
    <section className="admin-dashboard-panel card"><h2>{fr ? "Surveillance du stock" : "Pregled zaloge"}</h2><p>{data.lowStockCount} {fr ? "produits avec 5 unités ou moins" : "izdelkov s 5 kosi ali manj"}</p>{data.lowStock.length ? <ul className="ops-stock-list">{data.lowStock.map(product => <li key={product.slug}><Link href={`/admin/izdelki/${product.slug}`}>{product.name}<small>{product.sku}</small></Link><strong className={product.stock_quantity === 0 ? "ops-danger" : ""}>{product.stock_quantity}</strong></li>)}</ul> : <p className="ops-empty">{fr ? "Aucune alerte de stock sur les produits publiés." : "Za objavljene izdelke ni opozoril o zalogi."}</p>}<Link href="/admin/zaloga">{fr ? "Gérer les stocks" : "Upravljanje zaloge"} →</Link></section></div>
    <section className="admin-dashboard-panel card ops-sales"><h2>{fr ? "Encaissements par mois" : "Prejeta plačila po mesecih"}</h2><p>{fr ? "Six derniers mois, remboursements déduits des paiements du mois d’origine. Montants TTC." : "Zadnjih šest mesecev; vračila so odšteta od plačil v prvotnem mesecu. Zneski vključujejo DDV."}</p><div className="ops-chart" role="list">{data.monthlySales.map(month => <div role="listitem" className="ops-chart-item" key={month.month}><span>{money(month.cents)}</span><div className="ops-chart-track"><div style={{ height: `${Math.max(2, month.cents / max * 100)}%` }} /></div><small>{new Date(`${month.month}-15T12:00:00Z`).toLocaleDateString(fr ? "fr-FR" : "sl-SI", { month: "short", year: "2-digit" })}</small></div>)}</div></section>
  </>;
}
