"use client";
import { useActionState, useState } from "react";
import { useAdminLanguage } from "./admin-i18n";
import { saveAdminInquiry } from "@/actions/admin-inquiries";
import "./operations.css";
export type AdminInquiry = { id: string; name: string; email: string; phone: string | null; message: string; status: string; internal_note: string | null; product_slug: string | null; created_at: string; updated_at: string };
const statuses = { new: { fr: "Nouveau", sl: "Novo" }, in_review: { fr: "En cours", sl: "V obravnavi" }, responded: { fr: "Répondu", sl: "Odgovorjeno" }, closed: { fr: "Clôturé", sl: "Zaključeno" } };
export function InquiriesView({ items, canManage }: { items: AdminInquiry[] | null; canManage: boolean }) {
  const { locale } = useAdminLanguage(); const fr = locale === "fr"; const [filter, setFilter] = useState("");
  const visible = items?.filter(x => (!filter || x.status === filter));
  return <><header className="admin-page-heading"><div><p className="section-kicker">Bistrava</p><h1>{fr ? "Messages clients" : "Sporočila kupcev"}</h1><p>{fr ? "Consultez les demandes et suivez leur traitement. Les réponses s’envoient depuis votre messagerie." : "Preberite sporočila in spremljajte obravnavo. Odgovore pošljete iz svoje e-pošte."}</p></div></header><div className="ops-form"><label>{fr ? "Statut" : "Stanje"}<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">{fr ? "Tous" : "Vsa"}</option>{Object.entries(statuses).map(([key,label]) => <option key={key} value={key}>{label[locale]}</option>)}</select></label></div><div className="ops-cards" style={{ marginTop: 20 }}>{visible?.map(item => <article key={`${item.id}-${item.updated_at}`} className="admin-dashboard-panel card"><h2>{item.name}</h2><p><a href={`mailto:${item.email}`}>{item.email}</a>{item.phone ? ` · ${item.phone}` : ""}</p><p className="ops-meta">{new Date(item.created_at).toLocaleDateString(fr ? "fr-FR" : "sl-SI")} · {item.product_slug ?? "Bistrava"}</p><p style={{ whiteSpace: "pre-wrap" }}>{item.message}</p>{canManage ? <InquiryForm item={item} /> : <p>{statuses[item.status as keyof typeof statuses]?.[locale]}</p>}</article>)}</div>{!visible?.length ? <p className="ops-empty">{items === null ? (fr ? "Messages indisponibles pour le moment." : "Sporočila trenutno niso na voljo.") : (fr ? "Aucun message pour ce filtre." : "Za ta filter ni sporočil.")}</p> : null}<p className="ops-meta">{fr ? "100 messages les plus récents." : "Zadnjih 100 sporočil."}</p></>;
}
function InquiryForm({ item }: { item: AdminInquiry }) {
  const { locale } = useAdminLanguage(); const fr = locale === "fr";
  const [state, action, pending] = useActionState(saveAdminInquiry, { status: "idle" });
  return <form className="ops-form" action={action}><input type="hidden" name="id" value={item.id} /><input type="hidden" name="updatedAt" value={item.updated_at} /><label>{fr ? "Statut" : "Stanje"}<select name="status" defaultValue={item.status}>{Object.entries(statuses).map(([key,label]) => <option key={key} value={key}>{label[locale]}</option>)}</select></label><label>{fr ? "Note interne" : "Interna opomba"}<textarea name="note" defaultValue={item.internal_note ?? ""} maxLength={5000} /></label>{state.status !== "idle" ? <p role="status" className={`ops-notice ${state.status === "success" ? "" : "is-error"}`}>{state.status === "success" ? (fr ? "Enregistré." : "Shranjeno.") : (fr ? "Enregistrement impossible. Actualisez la page avant de réessayer." : "Shranjevanje ni uspelo. Osvežite stran in poskusite znova.")}</p> : null}<button disabled={pending} className="button button-primary">{pending ? "…" : fr ? "Enregistrer" : "Shrani"}</button></form>;
}
