"""Build an idempotent Supabase draft seed from the preserved SEO catalog."""

from __future__ import annotations

import json
import sys
from pathlib import Path


SPECIALIST_IDS = {
    "BIS-008", "BIS-016", "BIS-020", "BIS-029", "BIS-030", "BIS-038",
    "BIS-040", "BIS-041", "BIS-054", "BIS-060", "BIS-061", "BIS-064",
    "BIS-066", "BIS-067", "BIS-069", "BIS-071", "BIS-074", "BIS-076",
    "BIS-077", "BIS-078", "BIS-082", "BIS-083", "BIS-084", "BIS-086",
}

CATEGORIES = {
    "mehcalci-vode": (
        "Mehčalci vode",
        "Centralne naprave za zmanjšanje trdote vode.",
    ),
    "ciljna-zascita": (
        "Ciljna zaščita naprav",
        "Rešitve za posamezen porabnik ali odsek napeljave.",
    ),
    "meritve-in-montaza": (
        "Meritve in montaža",
        "Meritve in elementi za pripravo montaže mehčalca.",
    ),
    "sol-in-vzdrzevanje": (
        "Sol in vzdrževanje",
        "Potrošni material za regeneracijo in redno vzdrževanje.",
    ),
}


def sql(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_nullable(value: object) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return str(value).lower()
    if isinstance(value, (int, float)):
        return str(value)
    return sql(str(value))


def sql_json(value: object) -> str:
    return sql(json.dumps(value, ensure_ascii=False)) + "::jsonb"


def category_for(product: dict[str, object]) -> str:
    if product["categorySlug"] == "mehcalci-vode":
        return "mehcalci-vode"
    if product["id"] in {"BIS-029", "BIS-030"}:
        return "sol-in-vzdrzevanje"
    if product["id"] in {"BIS-054", "BIS-074", "BIS-084"}:
        return "ciljna-zascita"
    return "meritve-in-montaza"


def build(
    source_path: Path,
    supplier_price_path: Path,
    content_path: Path,
    media_path: Path,
    output_path: Path,
) -> None:
    products = json.loads(source_path.read_text(encoding="utf-8"))
    supplier_prices = json.loads(supplier_price_path.read_text(encoding="utf-8"))
    verified_content = json.loads(content_path.read_text(encoding="utf-8"))
    product_media = json.loads(media_path.read_text(encoding="utf-8"))
    supplier_prices_by_id = {price["id"]: price for price in supplier_prices}
    content_by_id = {content["id"]: content for content in verified_content}
    media_by_id = {media["id"]: media for media in product_media}
    selected = [product for product in products if product["id"] in SPECIALIST_IDS]
    if len(selected) != 24:
        raise ValueError(f"Expected 24 specialist products, found {len(selected)}")
    unknown_price_ids = set(supplier_prices_by_id) - SPECIALIST_IDS
    if unknown_price_ids:
        raise ValueError(f"Supplier prices contain unknown IDs: {sorted(unknown_price_ids)}")
    for name, records in {
        "supplier prices": supplier_prices_by_id,
        "verified content": content_by_id,
        "product media": media_by_id,
    }.items():
        if set(records) != SPECIALIST_IDS:
            raise ValueError(f"{name} must contain exactly the 24 specialist IDs")
    if any(len(media["images"]) != 4 for media in product_media):
        raise ValueError("Every specialist product must have exactly four images")

    lines = [
        "-- Generated by scripts/export-specialist-catalog-sql.py.",
        "-- Draft inventory quantity 5 reflects the owner's requested internal default.",
        "-- stock_status stays unverified and price_cents (Bistrava selling price) stays null.",
        "-- supplier_price_* stores dated public retail observations, not negotiated acquisition costs.",
        "begin;",
        "",
    ]
    for index, (slug, (name, description)) in enumerate(CATEGORIES.items()):
        lines.append(
            "insert into public.categories (name, slug, description, status, sort_order, published_at) "
            f"values ({sql(name)}, {sql(slug)}, {sql(description)}, 'active', {index + 1}, now()) "
            "on conflict (slug) do update set name = excluded.name, description = excluded.description, "
            "status = excluded.status, sort_order = excluded.sort_order, archived_at = null;"
        )
    lines.append("")

    for product in selected:
        category = category_for(product)
        content = content_by_id[product["id"]]
        media = media_by_id[product["id"]]
        typed = content.get("typed", {})
        supplier_price = supplier_prices_by_id[product["id"]]
        merchant_data = json.dumps(
            {
                "sourceUrl": product.get("researchSourceUrl"),
                "officialSourceUrl": supplier_price.get("sourceUrl"),
                "sourceRow": product.get("sourceRow"),
                "draftOnly": True,
                "draftImages": media["images"],
            },
            ensure_ascii=False,
        )
        install_required = typed.get(
            "installationRequired", category != "sol-in-vzdrzevanje"
        )
        sales_mode = "installation_required" if install_required else "buy_now"
        lines.extend(
            [
                "insert into public.products (",
                "  sku, name, name_sl, slug, brand, short_description, short_description_sl,",
                "  description, description_sl, status, technology, benefits, technical_specs,",
                "  price_cents, supplier_price_cents,",
                "  supplier_price_max_cents, supplier_price_includes_vat, supplier_price_source_name,",
                "  supplier_price_source_url, supplier_price_observed_at, supplier_price_note_sl,",
                "  vat_rate, currency, sales_mode, stock_status, stock_quantity,",
                "  household_size_min, household_size_max, resin_volume_liters, nominal_flow_lpm,",
                "  max_flow_lpm, connection_size, regeneration_mode, salt_consumption_kg, dimensions,",
                "  weight_kg, drain_required, electricity_required, bypass_included,",
                "  installation_required, warranty_months, certifications,",
                "  seo_title, seo_description, canonical_url, merchant_data",
                ") values (",
                f"  {sql(str(product['id']))}, {sql(str(content['nameSl']))}, {sql(str(content['nameSl']))},",
                f"  {sql(str(product['slug']))}, {sql(str(product['brand']))}, {sql(str(content['shortDescriptionSl']))}, {sql(str(content['shortDescriptionSl']))},",
                f"  {sql(str(content['descriptionSl']))}, {sql(str(content['descriptionSl']))}, 'draft', {sql(str(content['technology']))},",
                f"  {sql_json(content['highlightsSl'])}, {sql_json(content['technicalSpecifications'])}, null, {sql_nullable(supplier_price.get('priceCents'))},",
                f"  {sql_nullable(supplier_price.get('maxPriceCents'))}, {sql_nullable(supplier_price.get('includesVat'))}, {sql_nullable(supplier_price.get('sourceName'))},",
                f"  {sql_nullable(supplier_price.get('sourceUrl'))}, {sql_nullable(supplier_price.get('observedAt'))}, {sql_nullable(supplier_price.get('noteSl'))},",
                f"  22.00, 'EUR', '{sales_mode}', 'unverified', 5,",
                f"  {sql_nullable(typed.get('householdSizeMin'))}, {sql_nullable(typed.get('householdSizeMax'))}, {sql_nullable(typed.get('resinVolumeLiters'))}, {sql_nullable(typed.get('nominalFlowLitersPerMinute'))},",
                f"  {sql_nullable(typed.get('maxFlowLitersPerMinute'))}, {sql_nullable(typed.get('connectionSize'))}, {sql_nullable(typed.get('regenerationMode'))}, {sql_nullable(typed.get('saltConsumptionKg'))}, {sql_nullable(typed.get('dimensions'))},",
                f"  {sql_nullable(typed.get('weightKg'))}, {sql_nullable(typed.get('drainRequired'))}, {sql_nullable(typed.get('electricityRequired'))}, {sql_nullable(typed.get('bypassIncluded'))},",
                f"  {str(install_required).lower()}, {sql_nullable(typed.get('warrantyMonths'))}, {sql_json(typed.get('certifications', []))},",
                f"  {sql(str(content['seoTitle']))}, {sql(str(content['seoDescriptionSl']))},",
                f"  {sql('https://bistrava.com/izdelki/' + str(product['slug']))}, {sql(merchant_data)}::jsonb",
                ") on conflict (sku) do update set",
                "  name = excluded.name, name_sl = excluded.name_sl, slug = excluded.slug,",
                "  brand = excluded.brand, short_description = excluded.short_description,",
                "  short_description_sl = excluded.short_description_sl, description = excluded.description,",
                "  description_sl = excluded.description_sl, technology = excluded.technology,",
                "  benefits = excluded.benefits, technical_specs = excluded.technical_specs,",
                "  supplier_price_cents = excluded.supplier_price_cents,",
                "  supplier_price_max_cents = excluded.supplier_price_max_cents,",
                "  supplier_price_includes_vat = excluded.supplier_price_includes_vat,",
                "  supplier_price_source_name = excluded.supplier_price_source_name,",
                "  supplier_price_source_url = excluded.supplier_price_source_url,",
                "  supplier_price_observed_at = excluded.supplier_price_observed_at,",
                "  supplier_price_note_sl = excluded.supplier_price_note_sl,",
                "  sales_mode = excluded.sales_mode, stock_quantity = excluded.stock_quantity,",
                "  household_size_min = excluded.household_size_min, household_size_max = excluded.household_size_max,",
                "  resin_volume_liters = excluded.resin_volume_liters, nominal_flow_lpm = excluded.nominal_flow_lpm,",
                "  max_flow_lpm = excluded.max_flow_lpm, connection_size = excluded.connection_size,",
                "  regeneration_mode = excluded.regeneration_mode, salt_consumption_kg = excluded.salt_consumption_kg,",
                "  dimensions = excluded.dimensions, weight_kg = excluded.weight_kg,",
                "  drain_required = excluded.drain_required, electricity_required = excluded.electricity_required,",
                "  bypass_included = excluded.bypass_included, installation_required = excluded.installation_required,",
                "  warranty_months = excluded.warranty_months, certifications = excluded.certifications,",
                "  seo_title = excluded.seo_title,",
                "  seo_description = excluded.seo_description, canonical_url = excluded.canonical_url,",
                "  merchant_data = excluded.merchant_data, archived_at = null;",
                "",
                "insert into public.product_categories (product_id, category_id)",
                "select p.id, c.id from public.products p cross join public.categories c",
                f"where p.sku = {sql(str(product['id']))} and c.slug = {sql(category)}",
                "on conflict (product_id, category_id) do nothing;",
                "",
            ]
        )

    ids = ", ".join(sql(item) for item in sorted(SPECIALIST_IDS))
    lines.extend(
        [
            "update public.products",
            "set status = 'archived', archived_at = coalesce(archived_at, now())",
            f"where sku like 'BIS-%' and sku not in ({ids});",
            "",
            "commit;",
            "",
        ]
    )
    output_path.write_text("\n".join(lines), encoding="utf-8")


if __name__ == "__main__":
    if len(sys.argv) != 6:
        raise SystemExit(
            "usage: export-specialist-catalog-sql.py SOURCE_JSON SUPPLIER_PRICES_JSON "
            "CONTENT_JSON MEDIA_JSON OUTPUT_SQL"
        )
    build(
        Path(sys.argv[1]),
        Path(sys.argv[2]),
        Path(sys.argv[3]),
        Path(sys.argv[4]),
        Path(sys.argv[5]),
    )
